spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minicampus?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: your-database-username
    password: your-database-password

  spring:
    jpa:
      open-in-view: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
          transaction.coordinator_class: jta


  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@example.com
    password: your-password
    properties:
      mail:
        smtp:
          starttls:
            enable: true


logging:
  level:
    root: info


mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
